// the reason we're exporting these items from a js file is becuase there's no .ts typings files for these
// and you'll get an error when trying to import these in tsx components.

import {
    ChromaProvider,
    ChromaContext,
    Image,
    Input,
    Button,
    Icon,
    Sticky,
    Loader,
    InlineLoader,
    Alert,
    Text,
    Label,
    Card,
    CardContent,
    Message,
    Heading,
    Textarea,
    Form,
    Fieldset,
    Checkbox,
    DatePicker,
    List,
    InputFormat,
    ListItem,
    ListItemContent,
    Banner,
    Select,
    Price,
    Divider,
    Autocomplete,
    AutocompleteContainer,
    ButtonGroup,
    Badge,
    Logo,
    SegmentedControl,
    Link,
    Preloader
} from '@iag-packages/chroma-react/lib/components'

import { Main, Row, Column, Header, Footer, Container } from '@iag-packages/chroma-react/lib/layouts'

import {
    FormGroup,
    Tab,
    TabItem,
    Accordion,
    AccordionItem,
    InputGroup,
    Nav,
    NavItem,
    NavMenu,
    Modal,
    ToggleContent,
    AccordionWrapper,
} from '@iag-packages/chroma-react/lib/patterns'

import { getCssUrl, getAssetsPath } from '@iag-packages/chroma-react/lib/utils/cdn'

export {
    Modal,
    getCssUrl,
    getAssetsPath,
    Footer,
    Banner,
    Container,
    List,
    Select,
    ListItem,
    Header,
    Nav,
    NavItem,
    NavMenu,
    ChromaProvider,
    ChromaContext,
    Image,
    Button,
    Autocomplete,
    AutocompleteContainer,
    CardContent,
    Alert,
    Text,
    Input,
    Icon,
    Message,
    Sticky,
    Loader,
    Main,
    FormGroup,
    InputFormat,
    Tab,
    TabItem,
    Row,
    Column,
    Label,
    Card,
    ToggleContent,
    Heading,
    Accordion,
    AccordionItem,
    Textarea,
    Form,
    Fieldset,
    Checkbox,
    DatePicker as ChromaDatePicker, // So it doesn't clash with DatePicker from react-datepicker
    InlineLoader,
    Price,
    InputGroup,
    Divider,
    ListItemContent,
    ButtonGroup,
    Badge,
    Logo,
    SegmentedControl,
    Link,
    AccordionWrapper,
    Preloader
}
